# AndroidX（Compose/Room/WorkManager 等依赖必需）
android.useAndroidX=true
android.enableJetifier=true

# Kotlin 代码风格
kotlin.code.style=official

# 编译性能
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# 非传递型 R class（Compose 推荐）
android.nonTransitiveRClass=true
